### ISSUE TITLE
Incorrect parsing of await keyword inside class method

### ISSUE THREAD

**Issue by ghost** [MatAtBread/acorn-es7-plugin#12]
It breaks on this simple example: 

``` javascript
// Require acorn as usual
var acorn = require("acorn");
// Add the es7-plugin
require('acorn-es7-plugin')(acorn)

var code = `
class User extends Store {
   async fetchCurrent(){
    var user = await request.get('/api/users?action=me');
    this.update(user);
  }
}
`;
var ast = acorn.parse(code,{
    ranges: true,
    locations: true,
    ecmaVersion: 7,
    sourceType: "module",
    plugins: {
        asyncawait: true
    }
}) ;
// Show the AST
console.log(JSON.stringify(ast,null,2)) ;



SyntaxError: Unexpected token (4:21)
    at Parser.pp.raise (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseVarStatement (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:1948:8)
    at Parser.pp.parseStatement (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:1747:19)
    at Parser.parseStatement (/Users/dgfjk/Downloads/testacorn/node_modules/acorn-es7-plugin/acorn-es7-plugin.js:112:16)
    at Parser.pp.parseBlock (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseFunctionBody (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:610:22)
    at Parser.pp.parseMethod (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:579:8)
    at Parser.pp.parseClassMethod (/Users/dgfjk/Downloads/testacorn/node_modules/acorn/dist/acorn.js:2155:23)
```

**Comment by matAtWork** [comment]
Excellent catch. It's a bug. You can work around it (for now) by enabling the 'awaitAnywhere' options:

```
// Require acorn as usual
var acorn = require("acorn");
// Add the es7-plugin
require('acorn-es7-plugin')(acorn)

var code = `
class User extends Store {
   async fetchCurrent(){
    var user = await request.get('/api/users?action=me');
    this.update(user);
  }
}
`;
var ast = acorn.parse(code,{
    ranges: true,
    locations: true,
    ecmaVersion: 7,
    sourceType: "script",
    plugins:{
        asyncawait:{ 
            awaitAnywhere:true
        }
    }
}) ;
// Show the AST
console.log(JSON.stringify(ast,null,2)) ;
```

I'll try and post a fix in the next few days
